export const defaultState = {
    regions: [],
    allRegions: [],
    regionType: "boundary_uk_counties",
    climatePrediction: [],
    climateAverages: {},
    season: "annual",
    rcp: "rcp60",
    year: 2070,
    variable: "tas",
    isPredictionLoading: false,
    areAveragesLoading: false,
    selectedImpactHazard: "Extreme Storms",
    applyCoastalFilter: false,
};
