[tool.poetry]
name = "data"
version = "0.1.0"
description = "LCAT data module"
authors = ["Simon Kirby <s.kirby@exeter.ac.uk>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
geojson = "^3.3.0"
psycopg2 = "^2.9.12"
netcdf4 = "^1.7.3"
ipykernel = "^6.31.0"
jupyter = "^1.0.0"
matplotlib = "^3.11.1"
cartopy = "^0.25.0"
xarray = "^2024.11.0"
xmltodict = "^0.15.1"
boto3 = "^1.43.53"
python-dotenv = "^1.2.2"
geopandas = "^1.1.2"
scipy = "^1.17.1"
plotly = "^5.17.0"
beautifulsoup4 = "^4.15.0"
h5netcdf = "^1.6.3"
tqdm = "^4.69.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.22"
pytest = "^9.1.1"
pytest-cov = "^7.1.0"

[tool.ruff]
extend-exclude = ["*.ipynb", "tests/*"]
line-length = 150
target-version = "py310"

[tool.ruff.lint]
ignore = [
    "ANN001",  # Missing type annotation for function argument
    "ANN002",  # Missing type annotation for *args
    "ANN003",  # Missing type annotation for **kwargs
    "ANN201",  # Missing return type annotation for public function
    "ANN202",  # Missing return type annotation for private function
    "ANN204",  # Missing return type annotation for special method
    "ANN205",  # Missing return type annotation for staticmethod
    "ANN206",  # Missing return type annotation for classmethod
    "RET504",  # Unnecessary assignment before return
    "SIM108",  # Use ternary operator instead of if-else block
]
select = [
  "E", # pycodestyle
  "F", # Pyflakes
  "I", # isort
  "UP", # pyupgrade
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "PD", # pandas-vet
  "W", # pycodestyle
  "ANN", # flake8-annotations
  "ASYNC", #flake8-async
  "A", # flake8-builtins
  "C4", # flake8-comprehensions
  "ISC", # flake8-implicit-str-concat
  "ICN", # flake8-import-conventions
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "ARG", # flake8-unused-arguments
  "PD", # pandas-vet
  "R", # refactor
  "W", # warnings
  "PERF", #perflint
  "RUF", # ruff
]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
